String noun1 = "Happiness";
int number = 3;
String noun2 = " cats"; 
String verb = " running";
float percentage = 50.9;
String livingthing = "trees";
String location = "garden";
int streetnumber = 32;
String name = "Mary";
String fooditem = "bread";
float fraction = 0.5;
int randomnumber = 12;
float randomcashamount = 99.99;
String feeling = "nervous";

println("Today is National " + noun1 + " Day!");
println("I will be hanging out with " + number + noun2 + " to celebrate today.");
println("I will be" + verb + " all day long.");
println("About " + percentage + "% of the " + livingthing + " aren't aware of this day.");
println("There's a festival in the " + location + " on " + streetnumber + " Street and " + name + " Avenue.");
println("I brought some " + fooditem + " to the festival.");
println("But I by accidentally ate " + fraction + " before I could share with others.");
println("During the fesitval, I bought " + randomnumber + " raffle tickets and won " + randomcashamount + " dollars in cash.");
println("I have never been " + feeling + " in my life before.");